# SciKit Learn Preprocessing Overview

In [2]:
import numpy as np

In [3]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
data = np.random.randint(0,100,(10,2))

In [5]:
data

array([[16, 22],
       [53,  3],
       [70, 21],
       [80, 85],
       [16, 56],
       [89, 96],
       [76, 26],
       [24, 31],
       [65, 37],
       [17, 71]])

In [6]:
scaler_model = MinMaxScaler()

In [7]:
scaler_model.fit(data)

/Users/lepatrick714/anaconda/envs/ucrtf/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
scaler_model.transform(data)

array([[ 0.        ,  0.20430108],
       [ 0.50684932,  0.        ],
       [ 0.73972603,  0.19354839],
       [ 0.87671233,  0.88172043],
       [ 0.        ,  0.56989247],
       [ 1.        ,  1.        ],
       [ 0.82191781,  0.24731183],
       [ 0.10958904,  0.30107527],
       [ 0.67123288,  0.3655914 ],
       [ 0.01369863,  0.7311828 ]])

In [9]:
# In one step
result = scaler_model.fit_transform(data)

/Users/lepatrick714/anaconda/envs/ucrtf/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [10]:
result

array([[ 0.        ,  0.20430108],
       [ 0.50684932,  0.        ],
       [ 0.73972603,  0.19354839],
       [ 0.87671233,  0.88172043],
       [ 0.        ,  0.56989247],
       [ 1.        ,  1.        ],
       [ 0.82191781,  0.24731183],
       [ 0.10958904,  0.30107527],
       [ 0.67123288,  0.3655914 ],
       [ 0.01369863,  0.7311828 ]])

In [11]:
import pandas as pd

In [12]:
data = pd.DataFrame(data=np.random.randint(0,101,(50,4)),columns=['f1','f2','f3','label'])

In [13]:
data.head()

f1  f2  f3  label
0  78  80  65     28
1  51  43  93     35
2  84  17  65     88
3  58  31  97     70
4  43  47  40     44

In [14]:
x = data[['f1','f2','f3']] # Alternatively x = data.drop('label',axis=1)
y = data['label']

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [17]:
X_train.shape

(35, 3)

In [18]:
X_test.shape

(15, 3)

In [19]:
y_train.shape

(35,)

In [20]:
y_test.shape

(15,)

## Great Job!