In [1]:
print("HelloWorld")

HelloWorld


In [2]:
import numpy as np

In [3]:
my_list = [0, 1, 2, 3]

In [4]:
print(my_list)

[0, 1, 2, 3]


In [5]:
arr = np.array(my_list)

In [6]:
print(arr)

[0 1 2 3]


In [7]:
np.arrange(0, 10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0, 10, 2) 

array([0, 2, 4, 6, 8])

In [10]:
np.zero((5, 5))

AttributeError: module 'numpy' has no attribute 'zero'

In [11]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [12]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [13]:
np.random.randint(0, 10)

8

In [14]:
np.random.randint(0, 10 (3, 9))

TypeError: 'int' object is not callable

In [15]:
np.random.randint(0, 10, (3, 9))

array([[9, 7, 2, 5, 8, 1, 6, 9, 2],
       [0, 0, 8, 2, 6, 3, 1, 8, 9],
       [4, 4, 3, 6, 2, 2, 5, 6, 3]])

In [17]:
np.linspace(0,10, 6)

array([  0.,   2.,   4.,   6.,   8.,  10.])

In [18]:
arr2 = np.random.randint(0, 100, (10,10))

In [19]:
print(arr2)

[[ 2 76 60 85 15 61 48 58 35  9]
 [89  0  2 69 87 54 37 39 51 96]
 [81 15 12 79 47  6 33 24 80  1]
 [89  3 46 92 44 61 29 89  8 91]
 [38 97 77 70 26  1  5 47 76 98]
 [21 29 42 12 69 75 47 61 61  6]
 [60 32 68 28 85 97 58 99 22 99]
 [39 32 34 21 23 24 44 86 27 24]
 [91 56 90 33 46 39 77 16 34 42]
 [11 38 91 16  1 86 33 70 45 38]]


In [20]:
arr.max()

3

In [21]:
arr2.max()

99

In [22]:
arr2.min()

0

In [23]:
arr2.mean()

48.159999999999997

In [24]:
arr2.reshape(2,5)

ValueError: cannot reshape array of size 100 into shape (2,5)

In [25]:
mat = np.arange(0,100).reshape(10,10)

In [26]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
row = 0
col = 1


In [28]:
mat[row, col]

1

In [29]:
mat[:,col]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [30]:
mat[row,:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
mat > 50 

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]], dtype=bool)